---
- name: Add Apt Key for NodeJS PPA
  apt_key:
    id: 1655A0AB68576280
    keyserver: keyring.debian.org

- name: Add NodeJS 14 PPA
  apt_repository:
    repo: "deb https://deb.nodesource.com/node_14.x {{ ansible_distribution_release }} main"
    filename: nodesource

- name: Install npm
  apt:
    name:
      - nodejs

- name: Add build user
  user:
    name: build-user

- name: Download archive
  get_url:
    url: "https://github.com/Johni0702/mumble-web/archive/{{ version }}.tar.gz"
    dest: "{{ archive_file }}"
    checksum: "{{ checksum }}"
  become: False
  delegate_to: localhost

- name: Clean and create build directory
  file:
    path: "{{ build_dir }}"
    state: "{{ item }}"
  with_items:
    - absent
    - directory

- name: Unpack archive
  unarchive:
    src: "{{ archive_file }}"
    dest: "{{ build_base }}"
    owner: build-user

- name: Build mumble-web
  become_user: build-user
  command:
    cmd: npm install
    chdir: "{{ build_dir }}"

- name: Create deployment parent directory
  file:
    path: "{{ deploy_base }}"
    state: directory

- name: Clean and create deployment directory
  file:
    path: "{{ deploy_path }}"
    state: "{{ item }}"
  with_items:
    - absent
    - directory

- name: Deploy
  copy:
    remote_src: true
    src: "{{ build_dir }}/dist/"
    dest: "{{ deploy_path }}/"
    owner: www-data
    group: www-data
    mode: 'a=rX,u+w' # All readable, all can list directories but nothing is executable, user can write

- name: Save deployed version
  copy:
    content: "{{ version }}"
    dest: "{{ deployed_version_file }}"

- name: Delete build directory
  file:
    path: "{{ build_dir }}"
    state: absent
