---
- name: Calculate facts
  set_fact:
    deploy_path: "{{ (mumble_web.deploy_path | default('/var/www/mumble-web')) | regex_replace('\\/$', '') }}"
    version: "{{ mumble_web.version }}"
    checksum: "{{ mumble_web.checksum }}"
    reinstall: "{{ mumble_web.reinstall | default(false)}}"
    config: "{{ mumble_web.config | default({}) }}"

    archive_file: "{{ global_cache_dir }}/mumble-web-{{ mumble_web.version }}.tar.gz"
    build_dir: /opt/mumble-web-{{ mumble_web.version }}

- name: Retrieve deployed symlink target
  stat:
    path: "{{ deploy_path }}"
  register: _deployed_version_symlink_stat

- name: Install
  include_tasks: install.yml
  when: reinstall or (version not in (_deployed_version_symlink_stat.stat.lnk_target | default("")))

- name: Instantiate mumble-web config
  template:
    src: config.local.js.j2
    dest: "{{ deploy_path }}/config.local.js"
    owner: www-data
    group: www-data
    mode: 0644
