---
- name: Calculate facts
  set_fact:
    deploy_path: "{{ mumble_web_deploy_path | regex_replace('\\/$', '') }}"
    version: "{{ mumble_web_version }}"
    checksum: "{{ mumble_web_checksum }}"
    reinstall: "{{ mumble_web_reinstall }}"
    config: "{{ mumble_web_config }}"
    archive_file: "{{ global_cache_dir }}/mumble-web-{{ mumble_web_version }}.tar.gz"
    build_dir: /opt/mumble-web-{{ mumble_web_version }}

- name: Retrieve deployed symlink target
  stat:
    path: "{{ deploy_path }}"
  register: _deployed_version_symlink_stat

- name: Install
  include_tasks: install.yml
  when: reinstall or (version not in (_deployed_version_symlink_stat.stat.lnk_target | default("")))

- name: Instantiate mumble-web config
  template:
    src: config.local.js.j2
    dest: "{{ deploy_path }}/config.local.js"
    owner: www-data
    group: www-data
    mode: 0644
